subscriber:
    lidar:
        topic_name: /hesai/pandar_points
        policy_history: 2            #policy_history=1为Keep last，2为Keep all
        queue_size: 100000
    imu:
        topic_name: /imu/data
        policy_history: 2
        queue_size: 1000000
    gnss:
        topic_name: /rtk/data
        policy_history: 2
        queue_size: 1000000

publisher:
    lidar:
        topic_name: /preprocess/undistortion_points
        frame_id: laser_link
    gnss:
        topic_name: /preprocess/gnss/data
        frame_id: gnss_link
        

undistortion:
    lidar: 0